version: "3.9"

services:
  db:
    image: postgres:15
    container_name: techzone-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: techzone
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: amangil/techzone:v1
    container_name: techzone-server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/techzone
      SECRET_KEY: ${SECRET_KEY}
      ENV: production
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
    ports:
      - "8000:8000"

volumes:
  postgres_data: