name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #1 Get the code
      - name: Checkout code
        uses: actions/checkout@v3

      #2 Login to Docker Hub
      - name: Login to Docker-Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secretes.DOCKER_USERNAME}}
          password: ${{ secretes.DOCKER_PASSWORD}}

      #3 Extract version
      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      #4 Build Image and Push
      - name: Build Docker Image
        run: |
          docker build -t ${{secretes.DOCKER_USERNAME}}/techzone:${{ env.VERSION }} .
      
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/techzone:${{ env.VERSION }}